version: "3.3"

volumes:
  storage-static:

services:
  storage-service:
    build: .
    container_name: gostorage
    command: go run ./cmd/gostorage/main.go
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/usr/src/app/configs/dev.toml
    restart: unless-stopped
    volumes:
      - storage-static:/usr/src/app/static
